### ISSUE TITLE
Javascript

### ISSUE THREAD

**Issue by Lvl4Sword** [saurabhmarpadge/extramagnet#1]
How are you expecting to get around javascript being necessary to load the site?

**Comment by berabhishek** [comment]
It is ddos protected and the site is not loading unless the browser headers are checked. We can probably use the [urllib2](https://docs.python.org/2/library/urllib2.html)  library in python to create headers that will make it believe that a browser is requesting the webpage.

**Comment by saurabhmarpadge** [comment]
It could be solved using PhantomJS or Selenium. But it will slow down the process.

**Comment by Lvl4Sword** [comment]
@berabhishek 
That's not what I'm talking about at all.
If you go to the website and search for something the results require javascript to be loaded.
