### ISSUE TITLE
Handle dependency management efficiently

### ISSUE THREAD

**Issue by berabhishek** [saurabhmarpadge/extramagnet#2]
Create a file named  **requirements.txt** and place all the basic package names like __requests__ and __bs4__ that are required to run the code. So user can **pip install --update -r requirements.txt** and start running your code.
Also include a shell script that can install the commands in the system used in **os.system** call.

**Comment by saurabhmarpadge** [comment]
Ok, right user don't have to  take care of all the dependencies

**Comment by saurabhmarpadge** [comment]
Added Dependencies
